### PR TITLE
Local branch containing IPython extension

### PR DESCRIPTION
**Pull request by BrandonHaynes**

### CODE REVIEW

**Comment by domoritz** [comment]
@BrandonHaynes Can you fix the tests so that I can review?

**Comment by BrandonHaynes** [comment]
Note that tests exist for the extension, but are disabled when IPython isn't available -- I don't want to require a dependency on this module for those that are not using it.

**Comment by domoritz** [comment]
I'd just add it as a dev requirement to https://github.com/uwescience/myria-python/blob/master/requirements-dev.txt or install it manually in travis in https://github.com/uwescience/myria-python/blob/master/.travis.yml

**Comment by domoritz** [comment]
Looks awesome. I updated the example notebook a little bit. Before I merge this, can you fix the notebook `ipython extension examples`? I think it would be great to have an example and with https://github.com/blog/1995-github-jupyter-notebooks-3 we can even show them from github!!

**Comment by BrandonHaynes** [comment]
Most of the "plan-oriented" features that I added to `Myria-Python` won't get merged (because of the recent follow-on discussion around RACO), and so shouldn't be in the IPython notebook at this time.  (I think covers everything that is broken.)

I actually have a separate notebook that I'll be using for a demo that will be (IMO) more useful as an example.  Can we merge this and treat the notebook as a separate work item?  I won't have it wrapped up for another day or so.

**Comment by BrandonHaynes** [comment]
Demo IPython notebook has been pushed; I think this should cover most everything.

**Pull request merged**
